name: 'Deploy'     # Name of the action.
on:
  workflow_run:
    workflows: ["Python package"]
    types:
      - completed

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'  # Checkout the repository code.
      uses: 'actions/checkout@v1'

