name: 'Deployment'     # Name of the action.
on:
  workflow_run:
    workflows: ["Python package"]
    types: [completed]
    branches: [test_branch]

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'  # Checkout the repository code.
      uses: 'actions/checkout@v1'
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        labels: |
          org.opencontainers.image.vendor=Nokia
    - name: Download repository
      uses: actions/download-artifact@v2
      with:
        name: repository