name: 'Deployment'     # Name of the action.
on:
  workflow_run:
    workflows: ["Python package"]
    types: [completed]
    branches: ['*']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'  # Checkout the repository code.
      uses: 'actions/checkout@v1'
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        labels: |
          org.opencontainers.image.vendor=Nokia
 #   - name: Build variables
 #     id: vars
 #     run: |
 #       echo "::set-output name=repo::$GITHUB_REPOSITORY"
 #       echo "::set-output name=tag::$(git rev-parse --short "$GITHUB_SHA")"

    - name: Create kube config
      run: |
        mkdir -p $HOME/.kube/
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
    - name: Install helm
      run: |
        curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
        tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm
        helm version

    - name: Lint helm charts
      run: helm lint ${{ github.workspace }}/charts/koredump/
    - name: Deploy
      run: |
        docker ps | grep kube-apiserver
