name: 'Deployment'     # Name of the action.
on:
  workflow_run:
    workflows: ["Python package"]
    types: [completed]
    branches: ['*']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'  # Checkout the repository code.
      uses: 'actions/checkout@v1'
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        labels: |
          org.opencontainers.image.vendor=Nokia
    - name: Create kube config
      run: |
        mkdir -p $HOME/.kube/
        chmod 600 $HOME/.kube/config
    - name: Install helm
      run: |
        curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
        tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm
        helm version
